plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
    id 'idea'
    id 'com.diffplug.spotless' version '7.0.2'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

def enableEnhancedClassRedefinition = providers
        .gradleProperty('fdEnableEnhancedClassRedefinition')
        .map { it.toBoolean() }
        .getOrElse(false)

repositories {
    maven { url "https://maven.blamejared.com" }
    maven { url "https://maven.theillusivec4.top/" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            if (enableEnhancedClassRedefinition) {
                jvmArgument '-XX:+AllowEnhancedClassRedefinition'
            }
        }

        clientDebug {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            jvmArgument '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006'
            if (enableEnhancedClassRedefinition) {
                jvmArgument '-XX:+AllowEnhancedClassRedefinition'
            }
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
            jvmArgument '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'info'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    unitTest {
        enable()
        testedMod = mods.named(project.mod_id)
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
    testRuntimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "vazkii.patchouli:Patchouli:1.21.1-92-NEOFORGE"
    compileOnly "mezz.jei:jei-1.21.1-neoforge-api:${jei_version}"
    localRuntime "mezz.jei:jei-1.21.1-neoforge:${jei_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}:api"
    localRuntime "top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.11.4"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

spotless {
    java {
        target 'src/main/java/**/*.java'
        trimTrailingWhitespace()
        endWithNewline()
        leadingTabsToSpaces(4)
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
